### ISSUE TITLE
请教按需引入的问题

### ISSUE THREAD

**Issue by dwtom** [zine-fj/Vue3-Ts-Template#1]
按照vant官网上的说法

> 如果你在使用 TypeScript，可以使用 [ts-import-plugin](https://github.com/Brooooooklyn/ts-import-plugin) 实现按需引入。

我用ts-import-plugin引入组件完全无效，是不是就是因为这个问题所以你使用的还是`babel-plugin-import`

**Comment by zine-fj** [comment]
vant的官方文档里面有说配置 babel-plugin-import，可以去看一下

**Comment by dwtom** [comment]
> vant的官方文档里面有说配置 babel-plugin-import，可以去看一下

这个我知道，我上面说了，它在这个下面有一句话 如果在使用ts用 [ts-import-plugin](https://github.com/Brooooooklyn/ts-import-plugin) 实现按需引入，我按照vant-demo里面的ts引入发现完全没效果，所以我搜索了一下搜到了你的项目，然后看到了你用的是babel-plugin-import，我就想知道你有没有试过ts-import-plugin，看你直接用了babel-plugin-import所以我也还是直接在项目里面用这个

另外，方便留个联系方式交流一下技术吗

**Comment by zine-fj** [comment]
微信：Dec1_Fj
